# -*- coding: utf-8 -*-
"""email project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11vwcOdzKWv35IQrxIa37nz7i8JEJmMf9
"""

import smtplib

from email.mime.multipart import MIMEMultipart

from email.mime.text import MIMEText

import json

with open ('config.json') as config_file:
     data = json.load(config_file)

sender_email = data ['email_user']
password = data ['email_pass']

print (sender_email)
print (password)

recipients_email = ['manasikhairnar108@gmail.com', 'bhushankapadnis619@gmail.com', 'pallavikhairnar1294@gmail.com']

print (recipients_email)

Subject = "Subject of the mail"

body = """

      Hello,

      This is a text email sending from python script.

      Best Regards,
      Pallavi Khairnar

      """

smtp_server ="smtp.gmail.com"

port = 587

def send_email(recipients_email):
  try:
    msg = MIMEMultipart()
    msg['From'] = sender_email
    msg['To']= ",".join(recipients_email)
    msg['Subject']= Subject
    msg.attach(MIMEText(body, 'plain'))
    server = smtplib.SMTP(smtp_server, port)
    server.starttls()
    server.login(sender_email, password)
    server.sendmail(sender_email, recipients_email, msg.as_string())
    server.quit()
    print(f"email successfully send to {recipients_email}")
  except Exception as e:
    print(f"error sending email{recipients_email}:{e}")

send_email(recipients_email)

import streamlit as st

pip install streamlit